/* Change as needed 
CREATE DATABASE "server:c:/programme/suche/suchdb.gdb"
  USER "SYSDBA"
  PASSWORD "masterkey"
  PAGE_SIZE = 4096; */

/*  External Function declarations */
DECLARE EXTERNAL FUNCTION F_ADDMONTH
DATE, INTEGER
RETURNS DATE
ENTRY_POINT "AddMonth" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_ADDYEAR
DATE, INTEGER
RETURNS DATE
ENTRY_POINT "AddYear" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_AGEINDAYS
DATE, DATE
RETURNS INTEGER BY VALUE
ENTRY_POINT "AgeInDays" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_AGEINDAYSTHRESHOLD
DATE, DATE, INTEGER, INTEGER, INTEGER, INTEGER
RETURNS INTEGER BY VALUE
ENTRY_POINT "AgeInDaysThreshold" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_AGEINMONTHS
DATE, DATE
RETURNS INTEGER BY VALUE
ENTRY_POINT "AgeInMonths" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_AGEINMONTHSTHRESHOLD
DATE, DATE, INTEGER, INTEGER, INTEGER, INTEGER
RETURNS INTEGER BY VALUE
ENTRY_POINT "AgeInMonthsThreshold" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_AGEINWEEKS
DATE, DATE
RETURNS INTEGER BY VALUE
ENTRY_POINT "AgeInWeeks" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_AGEINWEEKSTHRESHOLD
DATE, DATE, INTEGER, INTEGER, INTEGER, INTEGER
RETURNS INTEGER BY VALUE
ENTRY_POINT "AgeInWeeksThreshold" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_BIGLRTRIM
CSTRING(1024) CHARACTER SET NONE
RETURNS CSTRING(1024) CHARACTER SET NONE
ENTRY_POINT "lrTrim" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_BIGSUBSTR
CSTRING(1024) CHARACTER SET NONE, CSTRING(1024) CHARACTER SET NONE
RETURNS INTEGER BY VALUE
ENTRY_POINT "SubStr" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_BLOBASPCHAR
BLOB
RETURNS CSTRING(1024) CHARACTER SET NONE
ENTRY_POINT "BlobAsPChar" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_BLOBLEFT
BLOB, INTEGER
RETURNS CSTRING(1024) CHARACTER SET NONE
ENTRY_POINT "BlobLeft" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_BLOBLINE
BLOB, INTEGER
RETURNS CSTRING(1024) CHARACTER SET NONE
ENTRY_POINT "BlobLine" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_BLOBMAXSEGMENTLENGTH
BLOB
RETURNS INTEGER BY VALUE
ENTRY_POINT "BlobMaxSegmentLength" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_BLOBMID
BLOB, INTEGER, INTEGER
RETURNS CSTRING(1024) CHARACTER SET NONE
ENTRY_POINT "BlobMid" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_BLOBRIGHT
BLOB, INTEGER
RETURNS CSTRING(1024) CHARACTER SET NONE
ENTRY_POINT "BlobRight" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_BLOBSEGMENTCOUNT
BLOB
RETURNS INTEGER BY VALUE
ENTRY_POINT "BlobSegmentCount" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_BLOBSIZE
BLOB
RETURNS INTEGER BY VALUE
ENTRY_POINT "BlobSize" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_CDOWLONG
DATE
RETURNS CSTRING(10) CHARACTER SET NONE
ENTRY_POINT "CDOWLong" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_CDOWSHORT
DATE
RETURNS CSTRING(4) CHARACTER SET NONE
ENTRY_POINT "CDOWShort" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_CHARACTER
INTEGER
RETURNS CSTRING(2) CHARACTER SET NONE
ENTRY_POINT "Character" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_CLOSEDEBUGGEROUTPUT

RETURNS INTEGER BY VALUE
ENTRY_POINT "CloseDebuggerOutput" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_CMONTHLONG
DATE
RETURNS CSTRING(10) CHARACTER SET NONE
ENTRY_POINT "CMonthLong" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_CMONTHSHORT
DATE
RETURNS CSTRING(4) CHARACTER SET NONE
ENTRY_POINT "CMonthShort" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_CRLF

RETURNS CSTRING(3) CHARACTER SET NONE
ENTRY_POINT "CRLF" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_DAYOFMONTH
DATE
RETURNS INTEGER BY VALUE
ENTRY_POINT "DayOfMonth" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_DAYOFWEEK
DATE
RETURNS INTEGER BY VALUE
ENTRY_POINT "DayOfWeek" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_DAYOFYEAR
DATE
RETURNS INTEGER BY VALUE
ENTRY_POINT "DayOfYear" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_DEBUG
CSTRING(1024) CHARACTER SET NONE
RETURNS INTEGER BY VALUE
ENTRY_POINT "Debug" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_DOLLARVAL
DOUBLE PRECISION
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "DollarVal" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_DOUBLEABS
DOUBLE PRECISION
RETURNS DOUBLE PRECISION BY VALUE
ENTRY_POINT "DoubleAbs" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_EVALUATECYCLEEXPRESSION
CSTRING(1024) CHARACTER SET NONE, INTEGER, DATE, DATE, DOUBLE PRECISION
RETURNS INTEGER BY VALUE
ENTRY_POINT "EvaluateCycleExpression" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_EVALUATEEXPRESSION
CSTRING(8196) CHARACTER SET NONE, CSTRING(8196) CHARACTER SET NONE
RETURNS CSTRING(8196) CHARACTER SET NONE
ENTRY_POINT "EvaluateExpression" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_FINDNTHWORD
CSTRING(8196) CHARACTER SET NONE, INTEGER
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "FindNthWord" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_FINDWORD
CSTRING(8196) CHARACTER SET NONE, INTEGER
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "FindWord" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_FINDWORDINDEX
CSTRING(8196) CHARACTER SET NONE, INTEGER
RETURNS INTEGER BY VALUE
ENTRY_POINT "FindWordIndex" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_FIXEDPOINT
DOUBLE PRECISION, INTEGER
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "FixedPoint" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_GENERATEFORMATTEDNAME
CSTRING(256) CHARACTER SET NONE, CSTRING(64) CHARACTER SET NONE, CSTRING(32) CHARACTER SET NONE, CSTRING(2) CHARACTER SET NONE, CSTRING(80) CHARACTER SET NONE, CSTRING(32) CHARACTER SET NONE
RETURNS CSTRING(256) CHARACTER SET NONE
ENTRY_POINT "GenerateFormattedName" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_GENERATESNDXINDEX
CSTRING(256) CHARACTER SET NONE
RETURNS CSTRING(6) CHARACTER SET NONE
ENTRY_POINT "GenerateSndxIndex" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_IBPASSWORD
CSTRING(32) CHARACTER SET NONE
RETURNS CSTRING(32) CHARACTER SET NONE
ENTRY_POINT "IBPassword" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_IBTEMPPATH

RETURNS CSTRING(1024) CHARACTER SET NONE
ENTRY_POINT "IBTempPath" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_ISDIVISIBLEBY
INTEGER, INTEGER
RETURNS INTEGER BY VALUE
ENTRY_POINT "IsDivisibleBy" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_LEFT
CSTRING(254) CHARACTER SET NONE, INTEGER
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "Left" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_LINEWRAP
CSTRING(1024) CHARACTER SET NONE, INTEGER, INTEGER
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "LineWrap" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_LRTRIM
CSTRING(254) CHARACTER SET NONE
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "lrTrim" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_LTRIM
CSTRING(254) CHARACTER SET NONE
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "lTrim" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_MAXDATE
DATE, DATE
RETURNS DATE
ENTRY_POINT "MaxDate" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_MID
CSTRING(32765) CHARACTER SET NONE, INTEGER, INTEGER
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "Mid" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_MINDATE
DATE, DATE
RETURNS DATE
ENTRY_POINT "MinDate" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_MODULO
INTEGER, INTEGER
RETURNS INTEGER BY VALUE
ENTRY_POINT "Modulo" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_MONTH
DATE
RETURNS INTEGER BY VALUE
ENTRY_POINT "Month" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_PADLEFT
CSTRING(254) CHARACTER SET NONE, CSTRING(10) CHARACTER SET NONE, INTEGER
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "PadLeft" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_PADRIGHT
CSTRING(254) CHARACTER SET NONE, CSTRING(10) CHARACTER SET NONE, INTEGER
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "PadRight" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_PROPERCASE
CSTRING(254) CHARACTER SET NONE
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "ProperCase" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_QUARTER
DATE
RETURNS INTEGER BY VALUE
ENTRY_POINT "Quarter" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_RIGHT
CSTRING(254) CHARACTER SET NONE, INTEGER
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "Right" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_ROUNDFLOAT
DOUBLE PRECISION, DOUBLE PRECISION
RETURNS DOUBLE PRECISION BY VALUE
ENTRY_POINT "RoundFloat" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_RTRIM
CSTRING(254) CHARACTER SET NONE
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "rTrim" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_SETDEBUGGEROUTPUT
CSTRING(1024) CHARACTER SET NONE
RETURNS INTEGER BY VALUE
ENTRY_POINT "SetDebuggerOutput" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_STRINGLENGTH
CSTRING(32765) CHARACTER SET NONE
RETURNS INTEGER BY VALUE
ENTRY_POINT "StringLength" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_STRIPDATE
DATE
RETURNS DATE
ENTRY_POINT "StripDate" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_STRIPSTRING
CSTRING(254) CHARACTER SET NONE, CSTRING(254) CHARACTER SET NONE
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "StripString" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_STRIPTIME
DATE
RETURNS DATE
ENTRY_POINT "StripTime" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_SUBSTR
CSTRING(254) CHARACTER SET NONE, CSTRING(254) CHARACTER SET NONE
RETURNS INTEGER BY VALUE
ENTRY_POINT "SubStr" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_TRUNCATE
DOUBLE PRECISION
RETURNS INTEGER BY VALUE
ENTRY_POINT "Truncate" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_VALIDATECYCLEEXPRESSION
CSTRING(1024) CHARACTER SET NONE, INTEGER
RETURNS INTEGER BY VALUE
ENTRY_POINT "ValidateCycleExpression" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_VALIDATENAMEFORMAT
CSTRING(256) CHARACTER SET NONE
RETURNS INTEGER BY VALUE
ENTRY_POINT "ValidateNameFormat" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_VALIDATEREGULAREXPRESSION
CSTRING(2048) CHARACTER SET NONE
RETURNS INTEGER BY VALUE
ENTRY_POINT "ValidateRegularExpression" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_VALIDATESTRINGINRE
CSTRING(2048) CHARACTER SET NONE, CSTRING(2048) CHARACTER SET NONE
RETURNS INTEGER BY VALUE
ENTRY_POINT "ValidateStringInRE" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_WEEKOFYEAR
DATE
RETURNS INTEGER BY VALUE
ENTRY_POINT "WeekOfYear" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_WOY
DATE
RETURNS CSTRING(254) CHARACTER SET NONE
ENTRY_POINT "WOY" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_YEAR
DATE
RETURNS INTEGER BY VALUE
ENTRY_POINT "Year" MODULE_NAME "FreeUDFLib.dll";

DECLARE EXTERNAL FUNCTION F_YEAROFYEAR
DATE
RETURNS INTEGER BY VALUE
ENTRY_POINT "YearOfYear" MODULE_NAME "FreeUDFLib.dll";

COMMIT WORK;

/* Domains */
CREATE DOMAIN DOM_ID AS INTEGER NOT NULL;
CREATE DOMAIN DOM_NAME AS VARCHAR(128) NOT NULL;
CREATE DOMAIN DOM_PASSWORD AS VARCHAR(8) NOT NULL;
CREATE DOMAIN DOM_BOOLEAN_T AS CHAR(1) DEFAULT 'T' NOT NULL;
CREATE DOMAIN DOM_BOOLEAN_F AS CHAR(1) DEFAULT 'F' NOT NULL;
CREATE DOMAIN DOM_DATE AS DATE NOT NULL;
CREATE DOMAIN DOM_DESCRIPTION AS VARCHAR(1024);
CREATE DOMAIN DOM_WORD AS VARCHAR(50);
CREATE DOMAIN DOM_CHAR AS CHAR(1);

COMMIT WORK;


