unit uPSI_ALMySqlWrapper;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_ALMySqlWrapper = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_TALMySqlLibrary(CL: TPSPascalCompiler);
procedure SIRegister_ALMySqlWrapper(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_TALMySqlLibrary(CL: TPSRuntimeClassImporter);
procedure RIRegister_ALMySqlWrapper(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   Windows
  ,ALMySqlWrapper
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_ALMySqlWrapper]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_TALMySqlLibrary(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TObject', 'TALMySqlLibrary') do
  with CL.AddClassN(CL.FindClass('TObject'),'TALMySqlLibrary') do
  begin
    RegisterProperty('mysql_affected_rows', '', iptrw);
    RegisterProperty('mysql_character_set_name', '', iptrw);
    RegisterProperty('mysql_close', '', iptrw);
    RegisterProperty('mysql_data_seek', '', iptrw);
    RegisterProperty('mysql_debug', '', iptrw);
    RegisterProperty('mysql_dump_debug_info', '', iptrw);
    RegisterProperty('mysql_eof', '', iptrw);
    RegisterProperty('mysql_errno', '', iptrw);
    RegisterProperty('mysql_error', '', iptrw);
    RegisterProperty('mysql_escape_string', '', iptrw);
    RegisterProperty('mysql_fetch_field', '', iptrw);
    RegisterProperty('mysql_fetch_field_direct', '', iptrw);
    RegisterProperty('mysql_fetch_fields', '', iptrw);
    RegisterProperty('mysql_fetch_lengths', '', iptrw);
    RegisterProperty('mysql_fetch_row', '', iptrw);
    RegisterProperty('mysql_field_seek', '', iptrw);
    RegisterProperty('mysql_field_tell', '', iptrw);
    RegisterProperty('mysql_free_result', '', iptrw);
    RegisterProperty('mysql_get_client_info', '', iptrw);
    RegisterProperty('mysql_get_host_info', '', iptrw);
    RegisterProperty('mysql_get_proto_info', '', iptrw);
    RegisterProperty('mysql_get_server_info', '', iptrw);
    RegisterProperty('mysql_info', '', iptrw);
    RegisterProperty('mysql_init', '', iptrw);
    RegisterProperty('mysql_insert_id', '', iptrw);
    RegisterProperty('mysql_kill', '', iptrw);
    RegisterProperty('mysql_list_dbs', '', iptrw);
    RegisterProperty('mysql_list_fields', '', iptrw);
    RegisterProperty('mysql_list_processes', '', iptrw);
    RegisterProperty('mysql_list_tables', '', iptrw);
    RegisterProperty('mysql_num_fields', '', iptrw);
    RegisterProperty('mysql_num_rows', '', iptrw);
    RegisterProperty('mysql_options', '', iptrw);
    RegisterProperty('mysql_ping', '', iptrw);
    RegisterProperty('mysql_query', '', iptrw);
    RegisterProperty('mysql_real_connect', '', iptrw);
    RegisterProperty('mysql_real_escape_string', '', iptrw);
    RegisterProperty('mysql_real_query', '', iptrw);
    RegisterProperty('mysql_refresh', '', iptrw);
    RegisterProperty('mysql_row_seek', '', iptrw);
    RegisterProperty('mysql_row_tell', '', iptrw);
    RegisterProperty('mysql_select_db', '', iptrw);
    RegisterProperty('mysql_ssl_set', '', iptrw);
    RegisterProperty('mysql_stat', '', iptrw);
    RegisterProperty('mysql_store_result', '', iptrw);
    RegisterProperty('mysql_thread_id', '', iptrw);
    RegisterProperty('mysql_use_result', '', iptrw);
    RegisterProperty('my_init', '', iptrw);
    RegisterProperty('mysql_thread_init', '', iptrw);
    RegisterProperty('mysql_thread_end', '', iptrw);
    RegisterProperty('mysql_thread_safe', '', iptrw);
    RegisterProperty('mysql_library_init', '', iptrw);
    RegisterProperty('mysql_library_end', '', iptrw);
    RegisterProperty('mysql_server_init', '', iptrw);
    RegisterProperty('mysql_server_end', '', iptrw);
    RegisterProperty('mysql_change_user', '', iptrw);
    RegisterProperty('mysql_field_count', '', iptrw);
    RegisterProperty('mysql_get_client_version', '', iptrw);
    RegisterProperty('mysql_send_query', '', iptrw);
    RegisterProperty('mysql_read_query_result', '', iptrw);
    RegisterProperty('mysql_autocommit', '', iptrw);
    RegisterProperty('mysql_commit', '', iptrw);
    RegisterProperty('mysql_get_server_version', '', iptrw);
    RegisterProperty('mysql_hex_string', '', iptrw);
    RegisterProperty('mysql_more_results', '', iptrw);
    RegisterProperty('mysql_next_result', '', iptrw);
    RegisterProperty('mysql_rollback', '', iptrw);
    RegisterProperty('mysql_set_character_set', '', iptrw);
    RegisterProperty('mysql_set_server_option', '', iptrw);
    RegisterProperty('mysql_shutdown', '', iptrw);
    RegisterProperty('mysql_sqlstate', '', iptrw);
    RegisterProperty('mysql_warning_count', '', iptrw);
    RegisterProperty('mysql_stmt_affected_rows', '', iptrw);
    RegisterProperty('mysql_stmt_attr_get', '', iptrw);
    RegisterProperty('mysql_stmt_attr_set', '', iptrw);
    RegisterProperty('mysql_stmt_bind_param', '', iptrw);
    RegisterProperty('mysql_stmt_bind_result', '', iptrw);
    RegisterProperty('mysql_stmt_close', '', iptrw);
    RegisterProperty('mysql_stmt_data_seek', '', iptrw);
    RegisterProperty('mysql_stmt_errno', '', iptrw);
    RegisterProperty('mysql_stmt_error', '', iptrw);
    RegisterProperty('mysql_stmt_execute', '', iptrw);
    RegisterProperty('mysql_stmt_fetch', '', iptrw);
    RegisterProperty('mysql_stmt_fetch_column', '', iptrw);
    RegisterProperty('mysql_stmt_field_count', '', iptrw);
    RegisterProperty('mysql_stmt_free_result', '', iptrw);
    RegisterProperty('mysql_stmt_init', '', iptrw);
    RegisterProperty('mysql_stmt_insert_id', '', iptrw);
    RegisterProperty('mysql_stmt_next_result', '', iptrw);
    RegisterProperty('mysql_stmt_num_rows', '', iptrw);
    RegisterProperty('mysql_stmt_param_count', '', iptrw);
    RegisterProperty('mysql_stmt_param_metadata', '', iptrw);
    RegisterProperty('mysql_stmt_prepare', '', iptrw);
    RegisterProperty('mysql_stmt_reset', '', iptrw);
    RegisterProperty('mysql_stmt_result_metadata', '', iptrw);
    RegisterProperty('mysql_stmt_row_seek', '', iptrw);
    RegisterProperty('mysql_stmt_row_tell', '', iptrw);
    RegisterProperty('mysql_stmt_send_long_data', '', iptrw);
    RegisterProperty('mysql_stmt_sqlstate', '', iptrw);
    RegisterProperty('mysql_stmt_store_result', '', iptrw);
    RegisterProperty('mysql_get_character_set_info', '', iptrw);
    RegisterMethod('Constructor Create( ApiVer : TALMySqlVersion_API)');
    RegisterMethod('Function Loaded : Boolean');
    RegisterMethod('Function Unload : Boolean');
    RegisterMethod('Function Load( const lib : AnsiString) : Boolean');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_ALMySqlWrapper(CL: TPSPascalCompiler);
begin
  CL.AddTypeS('uLongLong', 'LongLong');
 CL.AddConstantN('cALMySql_INVALIDELIBVERSION','String').SetString( 'Incorrect Database Server Version.');
 CL.AddConstantN('cALMySql_CANTLOADLIB','String').SetString( 'Can''t load library: %s.');
 CL.AddConstantN('CR_UNKNOWN_ERROR','LongInt').SetInt( 2000);
 CL.AddConstantN('CR_SOCKET_CREATE_ERROR','LongInt').SetInt( 2001);
 CL.AddConstantN('CR_CONNECTION_ERROR','LongInt').SetInt( 2002);
 CL.AddConstantN('CR_CONN_HOST_ERROR','LongInt').SetInt( 2003);
 CL.AddConstantN('CR_IPSOCK_ERROR','LongInt').SetInt( 2004);
 CL.AddConstantN('CR_UNKNOWN_HOST','LongInt').SetInt( 2005);
 CL.AddConstantN('CR_SERVER_GONE_ERROR','LongInt').SetInt( 2006);
 CL.AddConstantN('CR_VERSION_ERROR','LongInt').SetInt( 2007);
 CL.AddConstantN('CR_OUT_OF_MEMORY','LongInt').SetInt( 2008);
 CL.AddConstantN('CR_WRONG_HOST_INFO','LongInt').SetInt( 2009);
 CL.AddConstantN('CR_LOCALHOST_CONNECTION','LongInt').SetInt( 2010);
 CL.AddConstantN('CR_TCP_CONNECTION','LongInt').SetInt( 2011);
 CL.AddConstantN('CR_SERVER_HANDSHAKE_ERR','LongInt').SetInt( 2012);
 CL.AddConstantN('CR_SERVER_LOST','LongInt').SetInt( 2013);
 CL.AddConstantN('CR_COMMANDS_OUT_OF_SYNC','LongInt').SetInt( 2014);
 CL.AddConstantN('CR_NAMEDPIPE_CONNECTION','LongInt').SetInt( 2015);
 CL.AddConstantN('CR_NAMEDPIPEWAIT_ERROR','LongInt').SetInt( 2016);
 CL.AddConstantN('CR_NAMEDPIPEOPEN_ERROR','LongInt').SetInt( 2017);
 CL.AddConstantN('CR_NAMEDPIPESETSTATE_ERROR','LongInt').SetInt( 2018);
 CL.AddConstantN('CR_CANT_READ_CHARSET','LongInt').SetInt( 2019);
 CL.AddConstantN('CR_NET_PACKET_TOO_LARGE','LongInt').SetInt( 2020);
 CL.AddConstantN('CR_EMBEDDED_CONNECTION','LongInt').SetInt( 2021);
 CL.AddConstantN('CR_PROBE_SLAVE_STATUS','LongInt').SetInt( 2022);
 CL.AddConstantN('CR_PROBE_SLAVE_HOSTS','LongInt').SetInt( 2023);
 CL.AddConstantN('CR_PROBE_SLAVE_CONNECT','LongInt').SetInt( 2024);
 CL.AddConstantN('CR_PROBE_MASTER_CONNECT','LongInt').SetInt( 2025);
 CL.AddConstantN('CR_SSL_CONNECTION_ERROR','LongInt').SetInt( 2026);
 CL.AddConstantN('CR_MALFORMED_PACKET','LongInt').SetInt( 2027);
 CL.AddConstantN('CR_WRONG_LICENSE','LongInt').SetInt( 2028);
 CL.AddConstantN('CR_NULL_POINTER','LongInt').SetInt( 2029);
 CL.AddConstantN('CR_NO_PREPARE_STMT','LongInt').SetInt( 2030);
 CL.AddConstantN('CR_PARAMS_NOT_BOUND','LongInt').SetInt( 2031);
 CL.AddConstantN('CR_DATA_TRUNCATED','LongInt').SetInt( 2032);
 CL.AddConstantN('CR_NO_PARAMETERS_EXISTS','LongInt').SetInt( 2033);
 CL.AddConstantN('CR_INVALID_PARAMETER_NO','LongInt').SetInt( 2034);
 CL.AddConstantN('CR_INVALID_BUFFER_USE','LongInt').SetInt( 2035);
 CL.AddConstantN('CR_UNSUPPORTED_PARAM_TYPE','LongInt').SetInt( 2036);
 CL.AddConstantN('CR_SHARED_MEMORY_CONNECTION','LongInt').SetInt( 2037);
 CL.AddConstantN('CR_SHARED_MEMORY_CONNECT_REQUEST_ERROR','LongInt').SetInt( 2038);
 CL.AddConstantN('CR_SHARED_MEMORY_CONNECT_ANSWER_ERROR','LongInt').SetInt( 2039);
 CL.AddConstantN('CR_SHARED_MEMORY_CONNECT_FILE_MAP_ERROR','LongInt').SetInt( 2040);
 CL.AddConstantN('CR_SHARED_MEMORY_CONNECT_MAP_ERROR','LongInt').SetInt( 2041);
 CL.AddConstantN('CR_SHARED_MEMORY_FILE_MAP_ERROR','LongInt').SetInt( 2042);
 CL.AddConstantN('CR_SHARED_MEMORY_MAP_ERROR','LongInt').SetInt( 2043);
 CL.AddConstantN('CR_SHARED_MEMORY_EVENT_ERROR','LongInt').SetInt( 2044);
 CL.AddConstantN('CR_SHARED_MEMORY_CONNECT_ABANDONED_ERROR','LongInt').SetInt( 2045);
 CL.AddConstantN('CR_SHARED_MEMORY_CONNECT_SET_ERROR','LongInt').SetInt( 2046);
 CL.AddConstantN('CR_CONN_UNKNOW_PROTOCOL','LongInt').SetInt( 2047);
 CL.AddConstantN('CR_INVALID_CONN_HANDLE','LongInt').SetInt( 2048);
 CL.AddConstantN('CR_SECURE_AUTH','LongInt').SetInt( 2049);
 CL.AddConstantN('CR_FETCH_CANCELED','LongInt').SetInt( 2050);
 CL.AddConstantN('CR_NO_DATA','LongInt').SetInt( 2051);
 CL.AddConstantN('CR_NO_STMT_METADATA','LongInt').SetInt( 2052);
 CL.AddConstantN('CR_NO_RESULT_SET','LongInt').SetInt( 2053);
 CL.AddConstantN('CR_NOT_IMPLEMENTED','LongInt').SetInt( 2054);
 CL.AddConstantN('CR_SERVER_LOST_EXTENDED','LongInt').SetInt( 2055);
 CL.AddConstantN('CR_STMT_CLOSED','LongInt').SetInt( 2056);
 CL.AddConstantN('CR_NEW_STMT_METADATA','LongInt').SetInt( 2057);
 CL.AddConstantN('CR_ALREADY_CONNECTED','LongInt').SetInt( 2058);
 CL.AddConstantN('CR_AUTH_PLUGIN_CANNOT_LOAD','LongInt').SetInt( 2059);
 CL.AddConstantN('MYSQL_ERRMSG_SIZE','LongInt').SetInt( 512);
 CL.AddConstantN('SQLSTATE_LENGTH','LongInt').SetInt( 5);
 CL.AddConstantN('MYSQL_PORT','LongInt').SetInt( 3306);
 CL.AddConstantN('LOCAL_HOST','String').SetString( 'localhost');
 CL.AddConstantN('NOT_NULL_FLAG','LongInt').SetInt( 1);
 CL.AddConstantN('PRI_KEY_FLAG','LongInt').SetInt( 2);
 CL.AddConstantN('UNIQUE_KEY_FLAG','LongInt').SetInt( 4);
 CL.AddConstantN('MULTIPLE_KEY_FLAG','LongInt').SetInt( 8);
 CL.AddConstantN('BLOB_FLAG','LongInt').SetInt( 16);
 CL.AddConstantN('UNSIGNED_FLAG','LongInt').SetInt( 32);
 CL.AddConstantN('ZEROFILL_FLAG','LongInt').SetInt( 64);
 CL.AddConstantN('BINARY_FLAG','LongInt').SetInt( 128);
 CL.AddConstantN('ENUM_FLAG','LongInt').SetInt( 256);
 CL.AddConstantN('AUTO_INCREMENT_FLAG','LongInt').SetInt( 512);
 CL.AddConstantN('TIMESTAMP_FLAG','LongInt').SetInt( 1024);
 CL.AddConstantN('SET_FLAG','LongInt').SetInt( 2048);
 CL.AddConstantN('NUM_FLAG','LongInt').SetInt( 32768);
 CL.AddConstantN('PART_KEY_FLAG','LongInt').SetInt( 16384);
 CL.AddConstantN('GROUP_FLAG','LongInt').SetInt( 32768);
 CL.AddConstantN('UNIQUE_FLAG','LongInt').SetInt( 65536);
 CL.AddConstantN('BINCMP_FLAG','LongWord').SetUInt( $20000);
 CL.AddConstantN('GET_FIXED_FIELDS_FLAG','LongWord').SetUInt( $40000);
 CL.AddConstantN('FIELD_IN_PART_FUNC_FLAG','LongWord').SetUInt( $80000);
 CL.AddConstantN('FIELD_IN_ADD_INDEX','LongWord').SetUInt( $100000);
 CL.AddConstantN('FIELD_IS_RENAMED','LongWord').SetUInt( $200000);
 CL.AddConstantN('_CLIENT_LONG_PASSWORD','LongInt').SetInt( 1);
 CL.AddConstantN('_CLIENT_FOUND_ROWS','LongInt').SetInt( 2);
 CL.AddConstantN('_CLIENT_LONG_FLAG','LongInt').SetInt( 4);
 CL.AddConstantN('_CLIENT_CONNECT_WITH_DB','LongInt').SetInt( 8);
 CL.AddConstantN('_CLIENT_NO_SCHEMA','LongInt').SetInt( 16);
 CL.AddConstantN('_CLIENT_COMPRESS','LongInt').SetInt( 32);
 CL.AddConstantN('_CLIENT_ODBC','LongInt').SetInt( 64);
 CL.AddConstantN('_CLIENT_LOCAL_FILES','LongInt').SetInt( 128);
 CL.AddConstantN('_CLIENT_IGNORE_SPACE','LongInt').SetInt( 256);
 CL.AddConstantN('_CLIENT_CHANGE_USER','LongInt').SetInt( 512);
 CL.AddConstantN('_CLIENT_INTERACTIVE','LongInt').SetInt( 1024);
 CL.AddConstantN('_CLIENT_SSL','LongInt').SetInt( 2048);
 CL.AddConstantN('_CLIENT_IGNORE_SIGPIPE','LongInt').SetInt( 4096);
 CL.AddConstantN('_CLIENT_TRANSACTIONS','LongInt').SetInt( 8196);
 CL.AddConstantN('_CLIENT_RESERVED','LongInt').SetInt( 16384);
 CL.AddConstantN('_CLIENT_SECURE_CONNECTION','LongInt').SetInt( 32768);
 CL.AddConstantN('_CLIENT_MULTI_STATEMENTS','LongInt').SetInt( 65536);
 CL.AddConstantN('_CLIENT_MULTI_RESULTS','LongInt').SetInt( 131072);
 CL.AddConstantN('_CLIENT_PS_MULTI_RESULTS','LongInt').SetInt( 262144);
 CL.AddConstantN('_CLIENT_PLUGIN_AUTH','LongInt').SetInt( 524288);
 CL.AddConstantN('_CLIENT_SSL_VERIFY_SERVER_CERT','LongInt').SetInt( 1073741824);
 CL.AddConstantN('_CLIENT_REMEMBER_OPTIONS','LongWord').SetUInt( 2147483648);
 CL.AddConstantN('MYSQL_SHUTDOWN_KILLABLE_CONNECT','LongInt').SetInt( 1);
 CL.AddConstantN('MYSQL_SHUTDOWN_KILLABLE_TRANS','LongInt').SetInt( 2);
 CL.AddConstantN('MYSQL_SHUTDOWN_KILLABLE_LOCK_TABLE','LongInt').SetInt( 4);
 CL.AddConstantN('MYSQL_SHUTDOWN_KILLABLE_UPDATE','LongInt').SetInt( 8);
 CL.AddConstantN('STMT_FETCH_OK','LongInt').SetInt( 0);
 CL.AddConstantN('STMT_FETCH_ERROR','LongInt').SetInt( 1);
 CL.AddConstantN('STMT_FETCH_NO_DATA','LongInt').SetInt( 100);
 CL.AddConstantN('STMT_FETCH_DATA_TRUNC','LongInt').SetInt( 101);
  CL.AddTypeS('TMySqlOption', '( MYSQL_OPT_CONNECT_TIMEOUT, MYSQL_OPT_COMPRESS,'
   +' MYSQL_OPT_NAMED_PIPE, MYSQL_INIT_COMMAND, MYSQL_READ_DEFAULT_FILE, MYSQL_'
   +'READ_DEFAULT_GROUP, MYSQL_SET_CHARSET_DIR, MYSQL_SET_CHARSET_NAME, MYSQL_O'
   +'PT_LOCAL_INFILE, MYSQL_OPT_PROTOCOL, MYSQL_SHARED_MEMORY_BASE_NAME, MYSQL_'
   +'OPT_READ_TIMEOUT, MYSQL_OPT_WRITE_TIMEOUT, MYSQL_OPT_USE_RESULT, MYSQL_OPT'
   +'_USE_REMOTE_CONNECTION, MYSQL_OPT_USE_EMBEDDED_CONNECTION, MYSQL_OPT_GUESS'
   +'_CONNECTION, MYSQL_SET_CLIENT_IP, MYSQL_SECURE_AUTH, MYSQL_REPORT_DATA_TRU'
   +'NCATION, MYSQL_OPT_RECONNECT, MYSQL_OPT_SSL_VERIFY_SERVER_CERT, MYSQL_PLUG'
   +'IN_DIR, MYSQL_DEFAULT_AUTH )');
  CL.AddTypeS('_MYSQL_OPTIONS', 'record connect_timeout : UInt; read_timeout : '
   +'UInt; write_timeout : UInt; port : UInt; protocol : UInt; client_flag : UL'
   +'ong; host : PAnsiChar; user : PAnsiChar; password : PAnsiChar; unix_socket'
   +' : PAnsiChar; db : PAnsiChar; init_commands : Pointer; my_cnf_file : PAnsi'
   +'Char; my_cnf_group : PAnsiChar; charset_dir : PAnsiChar; charset_name : PA'
   +'nsiChar; ssl_key : PAnsiChar; ssl_cert : PAnsiChar; ssl_ca : PAnsiChar; ss'
   +'l_capath : PAnsiChar; ssl_cipher : PAnsiChar; shared_memory_base_name : PA'
   +'nsiChar; max_allowed_packet : ULong; use_ssl : Byte; compress : Byte; name'
   +'d_pipe : Byte; unused1 : Byte; unused2 : Byte; unused3 : Byte; unused4 : B'
   +'yte; methods_to_use : TMySqlOption; client_ip : PAnsiChar; secure_auth : B'
   +'yte; local_infile_init : Pointer; local_infile_read : Pointer; local_infil'
   +'e_end : Pointer; local_infile_error : Pointer; local_infile_userdata : Poi'
   +'nter; end');
  CL.AddTypeS('PZMySQLConnect', 'Pointer');
  CL.AddTypeS('PZMySQLResult', 'Pointer');
  CL.AddTypeS('PZMySQLRow', 'Pointer');
  CL.AddTypeS('PZMySQLField', 'Pointer');
  CL.AddTypeS('PZMySQLRowOffset', 'Pointer');
  CL.AddTypeS('PZMySqlPrepStmt', 'Pointer');
  CL.AddTypeS('PZMysqlBindArray', 'Pointer');
  CL.AddTypeS('TMYSQL_CLIENT_OPTIONS', '( CLIENT_LONG_PASSWORD, CLIENT_FOUND_RO'
   +'WS, CLIENT_LONG_FLAG, CLIENT_CONNECT_WITH_DB, CLIENT_NO_SCHEMA, CLIENT_COM'
   +'PRESS, CLIENT_ODBC, CLIENT_LOCAL_FILES, CLIENT_IGNORE_SPACE, CLIENT_CHANGE'
   +'_USER, CLIENT_INTERACTIVE, CLIENT_SSL, CLIENT_IGNORE_SIGPIPE, CLIENT_TRANS'
   +'ACTIONS, CLIENT_RESERVED, CLIENT_SECURE_CONNECTION, CLIENT_MULTI_STATEMENT'
   +'S, CLIENT_MULTI_RESULTS, CLIENT_PS_MULTI_RESULTS, CLIENT_PLUGIN_AUTH, CLIE'
   +'NT_OPT_20, CLIENT_OPT_21, CLIENT_OPT_22, CLIENT_OPT_23, CLIENT_OPT_24, CLI'
   +'ENT_OPT_25, CLIENT_OPT_26, CLIENT_OPT_27, CLIENT_OPT_28, CLIENT_OPT_29, CL'
   +'IENT_SSL_VERIFY_SERVER_CERT, CLIENT_REMEMBER_OPTIONS )');
  CL.AddTypeS('MYSQL_TIME', 'record year : UInt; month : UInt; day : UInt; hour'
   +' : UInt; minute : UInt; second : UInt; second_part : ULong; neg : Byte; en'
   +'d');
  SIRegister_TALMySqlLibrary(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_get_character_set_info_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_get_character_set_info := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_get_character_set_info_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_get_character_set_info; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_store_result_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_store_result := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_store_result_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_store_result; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_sqlstate_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_sqlstate := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_sqlstate_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_sqlstate; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_send_long_data_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_send_long_data := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_send_long_data_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_send_long_data; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_row_tell_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_row_tell := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_row_tell_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_row_tell; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_row_seek_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_row_seek := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_row_seek_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_row_seek; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_result_metadata_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_result_metadata := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_result_metadata_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_result_metadata; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_reset_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_reset := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_reset_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_reset; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_prepare_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_prepare := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_prepare_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_prepare; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_param_metadata_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_param_metadata := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_param_metadata_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_param_metadata; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_param_count_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_param_count := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_param_count_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_param_count; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_num_rows_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_num_rows := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_num_rows_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_num_rows; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_next_result_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_next_result := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_next_result_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_next_result; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_insert_id_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_insert_id := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_insert_id_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_insert_id; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_init_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_init := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_init_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_init; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_free_result_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_free_result := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_free_result_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_free_result; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_field_count_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_field_count := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_field_count_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_field_count; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_fetch_column_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_fetch_column := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_fetch_column_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_fetch_column; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_fetch_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_fetch := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_fetch_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_fetch; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_execute_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_execute := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_execute_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_execute; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_error_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_error := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_error_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_error; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_errno_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_errno := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_errno_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_errno; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_data_seek_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_data_seek := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_data_seek_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_data_seek; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_close_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_close := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_close_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_close; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_bind_result_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_bind_result := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_bind_result_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_bind_result; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_bind_param_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_bind_param := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_bind_param_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_bind_param; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_attr_set_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_attr_set := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_attr_set_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_attr_set; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_attr_get_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_attr_get := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_attr_get_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_attr_get; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_affected_rows_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stmt_affected_rows := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stmt_affected_rows_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stmt_affected_rows; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_warning_count_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_warning_count := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_warning_count_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_warning_count; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_sqlstate_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_sqlstate := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_sqlstate_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_sqlstate; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_shutdown_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_shutdown := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_shutdown_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_shutdown; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_set_server_option_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_set_server_option := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_set_server_option_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_set_server_option; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_set_character_set_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_set_character_set := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_set_character_set_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_set_character_set; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_rollback_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_rollback := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_rollback_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_rollback; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_next_result_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_next_result := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_next_result_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_next_result; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_more_results_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_more_results := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_more_results_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_more_results; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_hex_string_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_hex_string := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_hex_string_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_hex_string; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_get_server_version_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_get_server_version := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_get_server_version_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_get_server_version; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_commit_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_commit := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_commit_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_commit; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_autocommit_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_autocommit := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_autocommit_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_autocommit; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_read_query_result_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_read_query_result := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_read_query_result_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_read_query_result; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_send_query_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_send_query := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_send_query_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_send_query; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_get_client_version_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_get_client_version := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_get_client_version_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_get_client_version; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_field_count_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_field_count := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_field_count_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_field_count; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_change_user_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_change_user := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_change_user_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_change_user; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_server_end_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_server_end := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_server_end_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_server_end; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_server_init_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_server_init := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_server_init_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_server_init; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_library_end_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_library_end := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_library_end_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_library_end; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_library_init_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_library_init := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_library_init_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_library_init; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_thread_safe_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_thread_safe := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_thread_safe_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_thread_safe; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_thread_end_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_thread_end := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_thread_end_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_thread_end; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_thread_init_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_thread_init := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_thread_init_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_thread_init; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymy_init_W(Self: TALMySqlLibrary; const T: );
Begin Self.my_init := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymy_init_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.my_init; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_use_result_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_use_result := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_use_result_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_use_result; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_thread_id_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_thread_id := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_thread_id_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_thread_id; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_store_result_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_store_result := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_store_result_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_store_result; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stat_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_stat := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_stat_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_stat; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_ssl_set_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_ssl_set := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_ssl_set_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_ssl_set; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_select_db_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_select_db := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_select_db_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_select_db; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_row_tell_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_row_tell := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_row_tell_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_row_tell; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_row_seek_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_row_seek := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_row_seek_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_row_seek; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_refresh_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_refresh := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_refresh_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_refresh; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_real_query_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_real_query := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_real_query_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_real_query; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_real_escape_string_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_real_escape_string := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_real_escape_string_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_real_escape_string; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_real_connect_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_real_connect := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_real_connect_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_real_connect; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_query_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_query := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_query_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_query; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_ping_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_ping := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_ping_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_ping; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_options_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_options := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_options_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_options; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_num_rows_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_num_rows := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_num_rows_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_num_rows; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_num_fields_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_num_fields := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_num_fields_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_num_fields; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_list_tables_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_list_tables := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_list_tables_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_list_tables; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_list_processes_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_list_processes := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_list_processes_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_list_processes; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_list_fields_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_list_fields := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_list_fields_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_list_fields; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_list_dbs_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_list_dbs := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_list_dbs_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_list_dbs; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_kill_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_kill := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_kill_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_kill; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_insert_id_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_insert_id := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_insert_id_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_insert_id; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_init_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_init := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_init_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_init; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_info_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_info := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_info_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_info; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_get_server_info_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_get_server_info := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_get_server_info_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_get_server_info; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_get_proto_info_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_get_proto_info := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_get_proto_info_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_get_proto_info; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_get_host_info_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_get_host_info := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_get_host_info_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_get_host_info; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_get_client_info_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_get_client_info := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_get_client_info_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_get_client_info; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_free_result_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_free_result := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_free_result_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_free_result; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_field_tell_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_field_tell := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_field_tell_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_field_tell; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_field_seek_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_field_seek := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_field_seek_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_field_seek; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_fetch_row_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_fetch_row := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_fetch_row_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_fetch_row; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_fetch_lengths_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_fetch_lengths := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_fetch_lengths_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_fetch_lengths; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_fetch_fields_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_fetch_fields := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_fetch_fields_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_fetch_fields; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_fetch_field_direct_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_fetch_field_direct := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_fetch_field_direct_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_fetch_field_direct; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_fetch_field_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_fetch_field := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_fetch_field_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_fetch_field; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_escape_string_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_escape_string := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_escape_string_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_escape_string; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_error_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_error := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_error_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_error; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_errno_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_errno := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_errno_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_errno; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_eof_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_eof := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_eof_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_eof; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_dump_debug_info_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_dump_debug_info := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_dump_debug_info_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_dump_debug_info; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_debug_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_debug := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_debug_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_debug; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_data_seek_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_data_seek := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_data_seek_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_data_seek; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_close_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_close := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_close_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_close; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_character_set_name_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_character_set_name := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_character_set_name_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_character_set_name; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_affected_rows_W(Self: TALMySqlLibrary; const T: );
Begin Self.mysql_affected_rows := T; end;

(*----------------------------------------------------------------------------*)
procedure TALMySqlLibrarymysql_affected_rows_R(Self: TALMySqlLibrary; var T: );
Begin T := Self.mysql_affected_rows; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_TALMySqlLibrary(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(TALMySqlLibrary) do
  begin
    RegisterPropertyHelper(@TALMySqlLibrarymysql_affected_rows_R,@TALMySqlLibrarymysql_affected_rows_W,'mysql_affected_rows');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_character_set_name_R,@TALMySqlLibrarymysql_character_set_name_W,'mysql_character_set_name');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_close_R,@TALMySqlLibrarymysql_close_W,'mysql_close');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_data_seek_R,@TALMySqlLibrarymysql_data_seek_W,'mysql_data_seek');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_debug_R,@TALMySqlLibrarymysql_debug_W,'mysql_debug');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_dump_debug_info_R,@TALMySqlLibrarymysql_dump_debug_info_W,'mysql_dump_debug_info');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_eof_R,@TALMySqlLibrarymysql_eof_W,'mysql_eof');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_errno_R,@TALMySqlLibrarymysql_errno_W,'mysql_errno');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_error_R,@TALMySqlLibrarymysql_error_W,'mysql_error');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_escape_string_R,@TALMySqlLibrarymysql_escape_string_W,'mysql_escape_string');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_fetch_field_R,@TALMySqlLibrarymysql_fetch_field_W,'mysql_fetch_field');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_fetch_field_direct_R,@TALMySqlLibrarymysql_fetch_field_direct_W,'mysql_fetch_field_direct');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_fetch_fields_R,@TALMySqlLibrarymysql_fetch_fields_W,'mysql_fetch_fields');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_fetch_lengths_R,@TALMySqlLibrarymysql_fetch_lengths_W,'mysql_fetch_lengths');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_fetch_row_R,@TALMySqlLibrarymysql_fetch_row_W,'mysql_fetch_row');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_field_seek_R,@TALMySqlLibrarymysql_field_seek_W,'mysql_field_seek');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_field_tell_R,@TALMySqlLibrarymysql_field_tell_W,'mysql_field_tell');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_free_result_R,@TALMySqlLibrarymysql_free_result_W,'mysql_free_result');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_get_client_info_R,@TALMySqlLibrarymysql_get_client_info_W,'mysql_get_client_info');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_get_host_info_R,@TALMySqlLibrarymysql_get_host_info_W,'mysql_get_host_info');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_get_proto_info_R,@TALMySqlLibrarymysql_get_proto_info_W,'mysql_get_proto_info');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_get_server_info_R,@TALMySqlLibrarymysql_get_server_info_W,'mysql_get_server_info');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_info_R,@TALMySqlLibrarymysql_info_W,'mysql_info');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_init_R,@TALMySqlLibrarymysql_init_W,'mysql_init');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_insert_id_R,@TALMySqlLibrarymysql_insert_id_W,'mysql_insert_id');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_kill_R,@TALMySqlLibrarymysql_kill_W,'mysql_kill');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_list_dbs_R,@TALMySqlLibrarymysql_list_dbs_W,'mysql_list_dbs');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_list_fields_R,@TALMySqlLibrarymysql_list_fields_W,'mysql_list_fields');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_list_processes_R,@TALMySqlLibrarymysql_list_processes_W,'mysql_list_processes');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_list_tables_R,@TALMySqlLibrarymysql_list_tables_W,'mysql_list_tables');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_num_fields_R,@TALMySqlLibrarymysql_num_fields_W,'mysql_num_fields');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_num_rows_R,@TALMySqlLibrarymysql_num_rows_W,'mysql_num_rows');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_options_R,@TALMySqlLibrarymysql_options_W,'mysql_options');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_ping_R,@TALMySqlLibrarymysql_ping_W,'mysql_ping');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_query_R,@TALMySqlLibrarymysql_query_W,'mysql_query');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_real_connect_R,@TALMySqlLibrarymysql_real_connect_W,'mysql_real_connect');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_real_escape_string_R,@TALMySqlLibrarymysql_real_escape_string_W,'mysql_real_escape_string');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_real_query_R,@TALMySqlLibrarymysql_real_query_W,'mysql_real_query');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_refresh_R,@TALMySqlLibrarymysql_refresh_W,'mysql_refresh');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_row_seek_R,@TALMySqlLibrarymysql_row_seek_W,'mysql_row_seek');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_row_tell_R,@TALMySqlLibrarymysql_row_tell_W,'mysql_row_tell');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_select_db_R,@TALMySqlLibrarymysql_select_db_W,'mysql_select_db');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_ssl_set_R,@TALMySqlLibrarymysql_ssl_set_W,'mysql_ssl_set');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stat_R,@TALMySqlLibrarymysql_stat_W,'mysql_stat');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_store_result_R,@TALMySqlLibrarymysql_store_result_W,'mysql_store_result');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_thread_id_R,@TALMySqlLibrarymysql_thread_id_W,'mysql_thread_id');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_use_result_R,@TALMySqlLibrarymysql_use_result_W,'mysql_use_result');
    RegisterPropertyHelper(@TALMySqlLibrarymy_init_R,@TALMySqlLibrarymy_init_W,'my_init');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_thread_init_R,@TALMySqlLibrarymysql_thread_init_W,'mysql_thread_init');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_thread_end_R,@TALMySqlLibrarymysql_thread_end_W,'mysql_thread_end');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_thread_safe_R,@TALMySqlLibrarymysql_thread_safe_W,'mysql_thread_safe');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_library_init_R,@TALMySqlLibrarymysql_library_init_W,'mysql_library_init');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_library_end_R,@TALMySqlLibrarymysql_library_end_W,'mysql_library_end');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_server_init_R,@TALMySqlLibrarymysql_server_init_W,'mysql_server_init');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_server_end_R,@TALMySqlLibrarymysql_server_end_W,'mysql_server_end');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_change_user_R,@TALMySqlLibrarymysql_change_user_W,'mysql_change_user');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_field_count_R,@TALMySqlLibrarymysql_field_count_W,'mysql_field_count');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_get_client_version_R,@TALMySqlLibrarymysql_get_client_version_W,'mysql_get_client_version');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_send_query_R,@TALMySqlLibrarymysql_send_query_W,'mysql_send_query');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_read_query_result_R,@TALMySqlLibrarymysql_read_query_result_W,'mysql_read_query_result');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_autocommit_R,@TALMySqlLibrarymysql_autocommit_W,'mysql_autocommit');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_commit_R,@TALMySqlLibrarymysql_commit_W,'mysql_commit');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_get_server_version_R,@TALMySqlLibrarymysql_get_server_version_W,'mysql_get_server_version');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_hex_string_R,@TALMySqlLibrarymysql_hex_string_W,'mysql_hex_string');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_more_results_R,@TALMySqlLibrarymysql_more_results_W,'mysql_more_results');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_next_result_R,@TALMySqlLibrarymysql_next_result_W,'mysql_next_result');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_rollback_R,@TALMySqlLibrarymysql_rollback_W,'mysql_rollback');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_set_character_set_R,@TALMySqlLibrarymysql_set_character_set_W,'mysql_set_character_set');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_set_server_option_R,@TALMySqlLibrarymysql_set_server_option_W,'mysql_set_server_option');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_shutdown_R,@TALMySqlLibrarymysql_shutdown_W,'mysql_shutdown');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_sqlstate_R,@TALMySqlLibrarymysql_sqlstate_W,'mysql_sqlstate');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_warning_count_R,@TALMySqlLibrarymysql_warning_count_W,'mysql_warning_count');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_affected_rows_R,@TALMySqlLibrarymysql_stmt_affected_rows_W,'mysql_stmt_affected_rows');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_attr_get_R,@TALMySqlLibrarymysql_stmt_attr_get_W,'mysql_stmt_attr_get');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_attr_set_R,@TALMySqlLibrarymysql_stmt_attr_set_W,'mysql_stmt_attr_set');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_bind_param_R,@TALMySqlLibrarymysql_stmt_bind_param_W,'mysql_stmt_bind_param');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_bind_result_R,@TALMySqlLibrarymysql_stmt_bind_result_W,'mysql_stmt_bind_result');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_close_R,@TALMySqlLibrarymysql_stmt_close_W,'mysql_stmt_close');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_data_seek_R,@TALMySqlLibrarymysql_stmt_data_seek_W,'mysql_stmt_data_seek');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_errno_R,@TALMySqlLibrarymysql_stmt_errno_W,'mysql_stmt_errno');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_error_R,@TALMySqlLibrarymysql_stmt_error_W,'mysql_stmt_error');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_execute_R,@TALMySqlLibrarymysql_stmt_execute_W,'mysql_stmt_execute');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_fetch_R,@TALMySqlLibrarymysql_stmt_fetch_W,'mysql_stmt_fetch');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_fetch_column_R,@TALMySqlLibrarymysql_stmt_fetch_column_W,'mysql_stmt_fetch_column');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_field_count_R,@TALMySqlLibrarymysql_stmt_field_count_W,'mysql_stmt_field_count');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_free_result_R,@TALMySqlLibrarymysql_stmt_free_result_W,'mysql_stmt_free_result');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_init_R,@TALMySqlLibrarymysql_stmt_init_W,'mysql_stmt_init');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_insert_id_R,@TALMySqlLibrarymysql_stmt_insert_id_W,'mysql_stmt_insert_id');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_next_result_R,@TALMySqlLibrarymysql_stmt_next_result_W,'mysql_stmt_next_result');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_num_rows_R,@TALMySqlLibrarymysql_stmt_num_rows_W,'mysql_stmt_num_rows');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_param_count_R,@TALMySqlLibrarymysql_stmt_param_count_W,'mysql_stmt_param_count');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_param_metadata_R,@TALMySqlLibrarymysql_stmt_param_metadata_W,'mysql_stmt_param_metadata');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_prepare_R,@TALMySqlLibrarymysql_stmt_prepare_W,'mysql_stmt_prepare');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_reset_R,@TALMySqlLibrarymysql_stmt_reset_W,'mysql_stmt_reset');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_result_metadata_R,@TALMySqlLibrarymysql_stmt_result_metadata_W,'mysql_stmt_result_metadata');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_row_seek_R,@TALMySqlLibrarymysql_stmt_row_seek_W,'mysql_stmt_row_seek');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_row_tell_R,@TALMySqlLibrarymysql_stmt_row_tell_W,'mysql_stmt_row_tell');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_send_long_data_R,@TALMySqlLibrarymysql_stmt_send_long_data_W,'mysql_stmt_send_long_data');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_sqlstate_R,@TALMySqlLibrarymysql_stmt_sqlstate_W,'mysql_stmt_sqlstate');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_stmt_store_result_R,@TALMySqlLibrarymysql_stmt_store_result_W,'mysql_stmt_store_result');
    RegisterPropertyHelper(@TALMySqlLibrarymysql_get_character_set_info_R,@TALMySqlLibrarymysql_get_character_set_info_W,'mysql_get_character_set_info');
    RegisterVirtualConstructor(@TALMySqlLibrary.Create, 'Create');
    RegisterVirtualMethod(@TALMySqlLibrary.Loaded, 'Loaded');
    RegisterVirtualMethod(@TALMySqlLibrary.Unload, 'Unload');
    RegisterVirtualMethod(@TALMySqlLibrary.Load, 'Load');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_ALMySqlWrapper(CL: TPSRuntimeClassImporter);
begin
  RIRegister_TALMySqlLibrary(CL);
end;

 
 
{ TPSImport_ALMySqlWrapper }
(*----------------------------------------------------------------------------*)
procedure TPSImport_ALMySqlWrapper.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_ALMySqlWrapper(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_ALMySqlWrapper.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_ALMySqlWrapper(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
